

stages:
    - build
    - test
    - deploy
  
  build:
    stage: build
    script:
      - echo "Building the project..."
      - pip install -r src/requirements.txt
  
  test:
    stage: test
    script:
      - echo "Running tests..."
      - python -m unittest discover tests/  # Assuming you have a tests directory
  
  deploy:
    stage: deploy
    script:
      - echo "Deploying the model..."
      - python src/pca_model.py
    artifacts:
      paths:
        - pca_tips_viz.png  # Save the output visualization
  